name: Update Vmess Files

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  update_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run script
        run: |
          python script.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update vmess files" || echo "No changes to commit"
          git push
